name:  Build

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      APP_NAME: 'mibi-portal'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'SiLeBAT/mibi-portal-client'
          ref: 'develop'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.21.3' 
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check dependencies for vulnerabilities
        run: npm audit --audit-level=moderate

      - name: Static code analysis
        run: npm run lint 

      - name: Build the project
        run: npm run build:qa

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/${{ env.APP_NAME }}/


        env:
            TOKEN: ${{secrets.GITHUB_TOKEN}}