name: Mibi Client Build
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - task/mpc656
jobs:
  preparation:
    name: checkout code
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
        with:
          ref: task/mpc656
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
      - name: print node version
        run: node -v
      - name: print ls -al
        run: ls -al
      - name: print lastChange before
        run: grep lastChange package.json
      - name: replace lastChange in package.json with the commit date
        run: |
          out=$(git log -1 --format=%cd --date=iso | xargs)
          sed -i '/"mibiConfig"/,/\}/ s/"lastChange": "[^"]*"/"lastChange": "'"${out}"'"/' package.json
          grep lastChange package.json
      - name: install dependencies
        run: npm ci
      - name: run dependency check
        run: npm audit --audit-level=low --parseable

#           - name: Install dependencies
#         run: npm ci
#       - name: Run tests
#         run: npm test
#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get code
#         uses: actions/checkout@v3
#       - name: Install NodeJS
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: Install dependencies
#         run: npm ci
#       - name: Build project
#         run: npm run build
#       - name: Deploy
#         run: echo "Deploying ..."