name: Mibi Client CI
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - task/mpc656
env:
  ENVIRONMENT: qa
  AUDIT_FAIL_LEVEL: critiqual
  NODE_VERSION: 16.17.1

jobs:
  static-analysis:
    name: checkout code
    runs-on: ubuntu-latest

    steps:

      - name: Get code
        uses: actions/checkout@v5
        with:
          ref: task/mpc656

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: print node version
        run: node -v

      - name: print ls -al
        run: ls -al

      - name: print lastChange before
        run: grep lastChange package.json

      - name: replace lastChange in package.json with the commit date
        run: |
          out=$(git log -1 --format=%cd --date=iso | xargs)
          sed -i '/"mibiConfig"/,/\}/ s/"lastChange": "[^"]*"/"lastChange": "'"${out}"'"/' package.json
          grep lastChange package.json

      - name: install dependencies
        run: npm ci

      - name: print ENVIRONMENT
        run: echo $ENVIRONMENT
        
      - name: run dependency check qa
        id: dependencyCheckQA
        if: env.ENVIRONMENT == 'qa'
        run: npm audit --audit-level=low --parseable > dependency-check-output.log

      - name: run dependency check prod
        id: dependencyCheckPROD
        if: env.ENVIRONMENT == 'production'
        run: npm audit --audit-level=low --production --parseable > dependency-check-output.log

      - name: dependency check catch
        if: failure() && (steps.dependencyCheckQA.outcome == 'failure' || steps.dependencyCheckPROD.outcome == 'failure')
        run: npm audit --audit-level=${env.AUDIT_FAIL_LEVEL} --production --parseable > dependency-check-output-production.log

      - name: run static analysis
        run: npm run lint

#           - name: Install dependencies
#         run: npm ci
#       - name: Run tests
#         run: npm test
#   deploy:
#     needs: test
#     runs-on: ubuntu-latest
#     steps:
#       - name: Get code
#         uses: actions/checkout@v3
#       - name: Install NodeJS
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18
#       - name: Install dependencies
#         run: npm ci
#       - name: Build project
#         run: npm run build
#       - name: Deploy
#         run: echo "Deploying ..."