name: Mibi Client CI Continues
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - task/mpc656

jobs:
  static-analysis:
    uses: ./.github/workflows/mibi-client_ci.yml
    with:
      node-version: 16.17.1
